### ISSUE TITLE
Duration of maze generator

### ISSUE THREAD

**Issue by terry07** [raulorteg/ai-maze-python#1]
I had a time efficacy issue, but it was solved.

**Comment by raulorteg** [comment]
Hi, thanks for taking a look at this repo. I see you solved the issue, but wanted to add that I've just pushed a new version of the generator that its easier to use and its faster. If you dont want to visualize the process and just want to generate some number of mazes you can now run:
python maze_generator.py --display=0 --num_mazes=100
It takes around 0.1 or 0.2 second to generate each maze.

In case you are interested I wanted to make it faster, maybe add BFS algorithm, and make it a environment to test RL algorihtms and play a bit. Let me know if you are interested.
